export const SET_SCHEDULED_TWEETS = 'SET_SCHEDULED_TWEETS';
export const SET_TWEETED_TWEETS = 'SET_TWEETED_TWEETS';
export const ADD_TWEET = 'ADD_TWEET';
export const EDIT_TWEET = 'EDIT_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
