export default {
	auth: {
		user: {},
	},

	tweets: {
		scheduled: [
			// {
			// 	id: 1,
			// 	link: '1',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 2,
			// 	link: '2',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 3,
			// 	link: '3',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 4,
			// 	link: '4',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 5,
			// 	link: '5',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 6,
			// 	link: '6',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 7,
			// 	link: '7',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 8,
			// 	link: '8',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 9,
			// 	link: '9',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 10,
			// 	link: '10',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 11,
			// 	link: '11',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 12,
			// 	link: '12',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 13,
			// 	link: '13',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
			// {
			// 	id: 14,
			// 	link: '14',
			// 	content: 'Tomato Salad & Carrot',
			// 	number: '2',
			// 	duration: 'days',
			// },
		],
		archive: [],
	},
};
